### ISSUE TITLE
Seems to not be working in latest micro release (1.3.4)

### ISSUE THREAD

**Issue by zcotter** [samdmarshall/micro-fzf-plugin#1]
Hi there!

This plugin has been awesome, but i just upgraded micro from 1.3.3 to 1.3.4 and it seems to not be working in the new version. When I run `fzf` the file finder pops up, but when I select a file, it opens a file with no name instead of the file I selected.

I did a little debugging and found that the `HandleShellCommand("fzf", true, false)` part isn't returning any output in the new version of micro. I don't know much about lua/go/micro, so I'm not sure where to go from there. I'm just sticking with 1.3.3 for now.

Thanks!

**Comment by sum01** [comment]
This commit https://github.com/zyedidia/micro/commit/7f287b62fb59473228b6b5682da1451359993aa6 changes the `HandleShellCommand` parser, so that'll be where to look for the cause of the issue.

**Comment by samdmarshall** [comment]
I'm sorry but since I'm no longer using micro this is not being actively maintained. I am happy to accept PRs to fix it.

**Comment by giangm9** [comment]
use `RunInteractiveShell("fzf", false, true)` instead of `HandleShellCommand("fzf", true, false)` works

**Comment by useche** [comment]
I created a patch for this: https://github.com/samdmarshall/micro-fzf-plugin/compare/master...useche:patch-1

**Comment by samdmarshall** [comment]
Hey, so updates to this just appeared in my GitHub dashboard notifications -- it appears that I've missed a number of PR requests to update functionality. I've accepted one of them that appears to be a good rewrite, though, again I don't know if that fixes everything or not. I've been unable to maintain this as well as unable to keep up with PRs to the existing code so if someone else rather take ownership of this then i'm okay with that or having someone fork then I mark this as archived -- either way is fine with me. i'll try to keep a more active eye on this until something has been decided.

**Comment by adamluzsi** [comment]
Is it possible to somehow make the current version available trough micro's plugin install process ?

**Comment by samdmarshall** [comment]
i'm gonna reiterate that that I don't have the ability/time/anything to maintain this plugin or work on anything related to the micro text-editor. If someone wants to pickup  and run with this project then fork it and let me know so i can archive this repo to be read-only and direct people onto the currently maintained project.

**Comment by samdmarshall** [comment]
Okay, since nobody is responding I'm going to close all of my micro-related repos as archived (read-only). I'd offer my apologies for not being able to maintain these things going forward but it just so happens it ended up working out this way. If anyone still has interest in maintaining them, you can always fork and continue maintaining them yourselves.
